"""pitch class added

Revision ID: 54e3c334a8e9
Revises: 389be9788f9b
Create Date: 2019-09-20 14:16:56.289033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '54e3c334a8e9'
down_revision = '389be9788f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Pitchs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pitchs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Pitchs_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('Pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('downvote', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upvote', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='Pitchs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Pitchs_pkey')
    )
    op.drop_table('pitches')
    # ### end Alembic commands ###
