"""Initial MigrationD

Revision ID: d2b55e1f51c5
Revises: 54e3c334a8e9
Create Date: 2019-09-20 17:26:10.363571

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd2b55e1f51c5'
down_revision = '54e3c334a8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category', sa.String(length=255), nullable=False))
    op.drop_column('pitches', 'posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'category')
    # ### end Alembic commands ###
